sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -DsuiteXmlFile=testng.xml

before_install:
    - docker run -d -p 4445:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
    - docker run -d -p 4446:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210618
    - docker ps

cache:
  directories:
    - .autoconf
    - $HOME/.m2
