sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -DsuiteXmlFile=testng.xml

before_install:
    - curl https://raw.githubusercontent.com/zalando/zalenium/master/docs/docker/docker-compose.yaml > docker-compose.yaml
    - docker-compose up -d --force-recreate
    - docker-compose ps

cache:
  directories:
    - .autoconf
    - $HOME/.m2
