sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -DsuiteXmlFile=testng.xml

before_install:
    - curl https://gist.githubusercontent.com/rakesh-vardan/0c8d52e8faa9999abc2548fdf2632994/raw/76d038691fee323f27c42769d577862a8d6851c0/docker-compose.yml > docker-compose.yaml
    - docker-compose up -d --force-recreate
    - docker-compose ps

cache:
  directories:
    - .autoconf
    - $HOME/.m2
