dist: trusty
language: java

jdk:
  - oraclejdk8

before_script:
  - curl https://gist.githubusercontent.com/rakesh-vardan/c1dcf6531b826fad91f18c285d566a71/raw/ad90a18fe5e70f2d6aea06621b76d6e0329a4aab/docker-compose-sel.yml > docker-compose.yaml
  - docker-compose up -d
  - docker-compose ps

script:
  - mvn clean install -DsuiteXmlFile=testng.xml -Dbrowser=GRID_FIREFOX -DgridHubURL=http://localhost:4444/wd/hub

cache:
  directories:
    - .autoconf
    - $HOME/.m2