sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - lynx

script:
  - mvn clean install -DsuiteXmlFile=testng.xml

before_install:
    - docker run -d -p 4445:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
    - docker run -d -p 4446:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210618
    - docker ps

cache:
  directories:
    - .autoconf
    - $HOME/.m2

deploy:
  provider: releases
  api_key: ${api_key}
  file: "target/surefire-reports/emailable-report.html"
  skip_cleanup: true
  on:
    all_branches: true
    tags: false

#after_success:
#  - if [ -f /target/surefire-reports/emailable-report.html ]; then lynx -dump target/surefire-reports/emailable-report.html; fi